### ISSUE TITLE
OGMS:0000090 and OGMS:0000096 - Parent hierarchy instead of siblings?

### ISSUE THREAD

**Issue by lizumberfield** [OGMS/ogms#148]
OGMS:0000090 'Treatment' was recently imported into the Informed Consent Ontology following an evaluation of clinical consent forms. What is the rationale that 'Treatment' is a sibling of 'Health Care Process' (OGMS:0000096), rather than a child of? 

It seems to me that:
**[my recommendation]** 'Treatment'(OGMS:0000090) IS_A 'Health Care Process'(OGMS:0000096) 
just as 'Diagnostic Process'(OGMS:0000104) IS_A 'Health Care Process'(OGMS:0000096)

Thanks for considering.
[Elizabeth Umberfield](https://orcid.org/0000-0001-5029-1158)

**Comment by BAevermann** [comment]
Will move

**Comment by CDowland** [comment]
Here is the previous discussion on this that I mentioned during the meeting: https://github.com/OGMS/ogms/issues/88. 

It seems it was decided then that it would remain under 'planned process' instead of being moved. Perhaps the more recent discussion included a reason that outweighs those behind the previous decision, but I wanted to share the link in case you want to compare.

**Comment by lizumberfield** [comment]
I think I understand the qualms in the 2014 thread; however, I do not see 'roles' as included in the definition for [OGMS:0000096 'health care proces'](http://purl.obolibrary.org/obo/OGMS_0000096) (which I understand as the primary issue discussed in the 2014 thread). Furthermore, the notion of treatment *IS* included in the human-readable definition, which indicates some inconsistency if treatment remains a sibling of health care process:

> 'health care process: A planned process with the objective to improve the health status of a patient that directly involves the **_treatment,_** diagnosis, or prevention of disease or injury of a patient.'
